In [2]:
from numpy import *
import operator

#Simplest classifier:
def classify0(inX, dataSet, labels, k):
    dataSetSize = dataSet.shape[0]
    print dataSetSize
    diffMat = tile(inX, (dataSetSize,1)) - dataSet 
    print diffMat
    sqDiffMat = diffMat**2
    sqDistances = sqDiffMat.sum(axis=1)
    distances = sqDistances**0.5
    sortedDistIndicies = distances.argsort() 
    classCount={}
    for i in range(k):
        voteIlabel = labels[sortedDistIndicies[i]] 
        classCount[voteIlabel] = classCount.get(voteIlabel,0) + 1 
    sortedClassCount = sorted(classCount.iteritems(), 
     key=operator.itemgetter(1), reverse=True)
    return sortedClassCount[0][0]



# Text file to matrix code:
def file2matrix(filename): 
    fr = open(filename)
    numberOfLines = len(fr.readlines()) 
    returnMat = zeros((numberOfLines,3)) 
    classLabelVector = [] 
    fr = open(filename)
    index = 0
    for line in fr.readlines(): 
        line = line.strip()
        listFromLine = line.split('\t') 
        returnMat[index,:] = listFromLine[0:3] 
        classLabelVector.append(int(listFromLine[-1]))
        index += 1
    return returnMat,classLabelVector


datingDataMat,datingLabels = file2matrix('datingTestSet2.txt') 



#Auto normalizer

def autoNorm(dataSet):
    minVals = dataSet.min(0)
    maxVals = dataSet.max(0)
    ranges = maxVals - minVals
    normDataSet = zeros(shape(dataSet))
    m = dataSet.shape[0]
    normDataSet = dataSet - tile(minVals, (m,1))
    print tile(minVals,(m,1)).shape
    normDataSet = normDataSet/tile(ranges, (m,1)) 
    return normDataSet, ranges, minVals

autoNorm(datingDataMat)


def datingClassTest():
    hoRatio = 0.2
    datingDataMat,datingLabels = file2matrix('datingTestSet2.txt') 
    normMat, ranges, minVals = autoNorm(datingDataMat) 
    m = normMat.shape[0] 
    numTestVecs = int(m*hoRatio) 
    errorCount = 0.0
    for i in range(numTestVecs):
        classifierResult = classify0(normMat[i,:],normMat[numTestVecs:m,:],datingLabels[numTestVecs:m],3)
        print "the classifier came back with: %d, the real answer is: %d" % (classifierResult, datingLabels[i])
    if (classifierResult != datingLabels[i]): 
        errorCount += 1.0 
    print "the total error rate is: %f" % (errorCount/float(numTestVecs))

    
datingClassTest()

def classifyPerson():
    resultList = ['not at all','in small doses', 'in large doses'] 
    percentTats = float(raw_input("percentage of time spent playing video games?"))
    ffMiles = float(raw_input("frequent flier miles earned per year?")) 
    iceCream = float(raw_input("liters of ice cream consumed per year?")) 
    datingDataMat,datingLabels = file2matrix('datingTestSet2.txt') 
    normMat, ranges, minVals = autoNorm(datingDataMat) 
    inArr = array([ffMiles, percentTats, iceCream]) 
    classifierResult = classify0((inArr-minVals)/ranges,normMat,datingLabels,3)
    print "You will probably like this person: ", resultList[classifierResult - 1]


classifyPerson()

(1000L, 3L)
(1000L, 3L)
800
[[ 0.21157407  0.12561987 -0.25846912]
 [ 0.18738291  0.28096467 -0.21754986]
 [ 0.27697128  0.39805139 -0.16196548]
 ...
 [ 0.15716587 -0.11105154  0.0515386 ]
 [-0.07878562 -0.03860311  0.13332873]
 [-0.03108258  0.0212423  -0.22338451]]
the classifier came back with: 3, the real answer is: 3
800
[[-0.07801869  0.06952315  0.16644151]
 [-0.10220985  0.22486794  0.20736077]
 [-0.01262148  0.34195467  0.26294515]
 ...
 [-0.1324269  -0.16714827  0.47644923]
 [-0.36837838 -0.09469984  0.55823936]
 [-0.32067534 -0.03485443  0.20152612]]
the classifier came back with: 2, the real answer is: 2
800
[[ 0.04867814 -0.20350629 -0.34630637]
 [ 0.02448698 -0.04816149 -0.3053871 ]
 [ 0.11407536  0.06892523 -0.24980273]
 ...
 [-0.00573006 -0.4401777  -0.03629864]
 [-0.24168155 -0.36772927  0.04549149]
 [-0.1939785  -0.30788386 -0.31122175]]
the classifier came back with: 1, the real answer is: 1
800
[[ 0.58644944  0.35604856 -0.56831336]
 [ 0.56225828  0.51139335 -0.5273

percentage of time spent playing video games?10
frequent flier miles earned per year?10000
liters of ice cream consumed per year?0.5
(1000L, 3L)
1000
[[-0.33876393  0.07997496 -0.26791929]
 [-0.04917117  0.13607168 -0.69282992]
 [-0.175868    0.40910111 -0.18008205]
 ...
 [-0.18159806 -0.03107659 -0.21638069]
 [-0.41754955  0.04137184 -0.13459056]
 [-0.3698465   0.10121725 -0.4913038 ]]
You will probably like this person:  in small doses
